### ISSUE TITLE
add support for uploading distribution files

### ISSUE THREAD

**Issue by ngoldman** [ngoldman/gh-release#1]
i.e. a new option:

* `zip`: zip and upload dist using `files` array from `package.json`

caveats:

1. may require a build step, as some files in `files` may be `.gitignore`'d
1. may require force adding some `files` and pushing up a temporary release branch to ensure built files are included in the release but kept out of `master`

This supports two use cases:

1. A package needs to be distributed with a build but you don't want to check that build into source control over and over (solution: automate this).
1. A release needs to include a zip of the repo (solution: automate that).

**Comment by ngoldman** [comment]
This is something @kneemer & @paulcpederson want in particular (PRs welcome :smile_cat:)

**Comment by bcomnes** [comment]
I could try putting this together if I can see someone do it all by hand first.

**Comment by paulcpederson** [comment]
@ngoldman @bcomnes I think this is almost *2* options:

1. Do you want to create a zip and attach it to the release? `--zip -z`
2. Do you want to only include files listed in the `files` key in your distribution? `--files -f` maybe...

**Comment by paulcpederson** [comment]
Also, as far as a build step, would it be safe to just run `npm prebulish` and tell people to make sure all of their compilation happens there?

**Comment by bcomnes** [comment]
@paulcpederson what is your ideal workflow in your specific situation?

**Comment by paulcpederson** [comment]
Here's a situation I'm in with several different libraries:

- I'm writing code that needs to be compiled (sass -> css, es6 -> es5, etc...)
- Committing the compiled files is a pain because it leads to lots of merge conflicts (especially in minified files) and the pr's are really *noisy* because every time you change anything it is reported in two or three places.
- Locally there is some task runner (npm, grunt, gulp, etc) that compiles these files on the fly

When it comes to releases, not committing the built file is problematic because then users of your library can't just `npm install` and instantly have everything ready to go.

---

The ideal workflow is to have the best of both worlds:
1. Don't add compiled files to version control
2. run `gh-release -f` and have that automatically include, tag, and push the built files 

---

A workflow for this would be the following (shell version plagarized from the leaflet build script):

```
# Get current version (from package.json)
 VERSION=$(node --eval "console.log(require('./package.json').version);")

# Checkout a new temporary branch (probably named gh-release or some such)
git checkout -b gh-release

# Build and test (probably optional for this module, though maybe configurable)
npm test
npm run prepublish

# Force add files from package.json 'files' key
git add dist/whatever.js dist/whatever.min.js -f

# Commit changes with a versioned commit message
git commit -m "build $VERSION"

# Tag with the version (eg v0.0.3)
git tag $VERSION

# Push the tags to GitHub
git push --tags git@github.com:yourname/yourrepo.git $VERSION

# this is where you would npm publish (not sure we want to do that..)

# Cleanup
git checkout master
git branch -D build
```

**Comment by bcomnes** [comment]
Ahhhrg.  I wrote a response and didn't save it.

To specify this a bit more:
- When packaging a release with build results, gh-release will only (at least to start with) release on a tag branch like in the leaflet example.
- gh-release will take care of creating that branch and tag and pushing to origin
- gh-release will test to see the build step is completed before it is run (how?)
- How will gh-release know which files to force add?  flags, gh-release options in package.json?

**Comment by bcomnes** [comment]
I need to review this article again, but I have it noted as describing a sane packaging strategy that include build steps: https://medium.com/@brianleroux/es6-modules-amd-and-commonjs-c1acefbe6fc0

I'll try and extract possibly useful information from it soon.

**Comment by paulcpederson** [comment]
After reading @ngoldman 's goals for this project and talking to him a bit, I almost wonder if all this isn't a bit much for gh-release. Maybe this is a separate module? Does this violate the 'do one thing and do it well' philosophy? I don't know. Do other people even need this or am I the weirdest person in the world?

:confused:

**Comment by ngoldman** [comment]
@paulcpederson since github releases can include files it makes sense for `gh-release` to cover that too. However maybe supporting complex build steps for front-end packages is out of the scope of the project.

I think if we can support the zip+upload step, we're already offering something useful enough to meet the latter use case halfway.

A second package could use `gh-release` programmatically and handle the use case specific to front-end packages that want distribution files in their releases but not in version control.

**Comment by bcomnes** [comment]
The build step should probably be handled by something else, or gh-release is a step in some kind of in a release build.

I'm thinking there would be 3 scenarios:

- A regular release (like how it works now).  The release download is just an archive of the source code.
- A built release.  An array of files is provided to gh-release as an option.  Gh-release creates a tag-branch and force commits these files to it.  The release download is a snapshot of the source plus the built files.
- If some kind of `zip` option is also set along side the file release array in option two, take only those files and zip/tar them and use that for the release download.

What do you all think?

**Comment by paulcpederson** [comment]
@ngoldman right, that makes sense. 

So there could be another module that depends on gh-release that essentially kicks off the branching gymnastics and then once everything is tagged and push correctly, it just calls gh-release. I think that makes sense. 

If that's the case, then we could definitely add `--zip` to gh-release. I think we should still use the `files` array in `package.json` for the content of the zip, because that would make the zip mirror what will be distributed on npm. 

The other options for the zip are:

1. Just zip the entire project
2. Zip a specific folder
3. Zip everything in the `files` array
4. Zip everything except what is precluded in the `.npmignore`

**Comment by ngoldman** [comment]
++ for mirroring what's distributed on npm by default (regardless of scenario). we can start with that then add options as necessary.

**Comment by paulcpederson** [comment]
I think npm also automatically includes `LICENSE`, `CHANGELOG`, and `README` as well, which is probably something we should figure out and do as well.

**Comment by ngoldman** [comment]
I bet we can just find the code or module npm is using for this and use that.

**Comment by paulcpederson** [comment]
lol, my browser is currently at https://github.com/npm/npm/blob/master/lib/publish.js

**Comment by paulcpederson** [comment]
Wow, this is very interesting: https://github.com/npm/npm/blob/448efd0eaa6f97af0889bf47efc543a1ea2f8d7e/doc/misc/npm-developers.md#keeping-files-out-of-your-package

Apparently adding files that are gitignored to your npm package is as easy as adding a blank `.npmignore` file. Very interesting.

**Comment by ngoldman** [comment]
@paulcpederson how is https://github.com/paulcpederson/unignored coming along? I'm guessing the point is to reliably get the files npm would publish as an array or something like that, possibly for use in a `gh-release`-dependent project?

**Comment by ngoldman** [comment]
I think the consensus is gh-release should support adding assets to a release (reference here: https://developer.github.com/v3/repos/releases/#upload-a-release-asset, tested here: https://github.com/bcomnes/gh-release-test/releases/tag/v1.0.4) and leave the branching, building, committing, and pushing of a release build to another project. I'll try to get to this soon (PRs welcome).

**Comment by ngoldman** [comment]
I'm also realizing part of this use case is totally unnecessary since github releases automatically generate a zip (https://github.com/ngoldman/gh-release/archive/v1.1.2.zip)  and tarball (https://github.com/ngoldman/gh-release/archive/v1.1.2.tar.gz) which are listed right under the release.

![screen shot 2015-03-21 at 6 04 40 pm](https://cloud.githubusercontent.com/assets/427322/6767579/caa6931e-cff4-11e4-98d3-31050c1eb7e5.png)

![](http://memecrunch.com/meme/ZMZ8/whoops/image.png)

Being able to upload one or more release assets is still a valid feature request though.

**Comment by paulcpederson** [comment]
Yeah, I agree it doesn't make sense to zip the whole repo. If we add an attachment capability it should be basically a `dist` folder. 

Unignored is fully functional. I have a theory about how all this should work, but it is far outside the scope of gh-release. Maybe in versioneer?

**Comment by ngoldman** [comment]
@paulcpederson there are issues, check https://github.com/paulcpederson/unignored/issues/1 & https://github.com/paulcpederson/unignored/issues/2

**Comment by paulcpederson** [comment]
Cool. =>  [latest release](https://www.npmjs.com/package/pkgfiles) ... :grimacing:

**Comment by bcomnes** [comment]
Here is another example of a build release process: https://github.com/maxogden/monu/blob/master/publish-release.js

**Comment by bcomnes** [comment]
Looks like it was turned into its own module https://github.com/remixz/publish-release

**Comment by ngoldman** [comment]
hmm dang

**Comment by ngoldman** [comment]
he's doing a lot of stuff very similarly to us, we had worked together :(

**Comment by paulcpederson** [comment]
yeah, that doesn't really do anything that gh-release doesn't do other than uploading assets.

**Comment by ngoldman** [comment]
@paulcpederson there's some differences in methodology and `publish-release`'s programmatic version is emitting events. It's also doing the $EDITOR thing we were discussing.

@remixz :wave:

**Comment by ngoldman** [comment]
I think it came from helping out @maxogden with github.com/maxogden/monu which requires a build with the release for an app kind of thing

**Comment by remixz** [comment]
@ngoldman hi! dang, i wish we did work together. you're totally correct in that it came from monu, max wanted to use the publishing workflow on some other projects, so i made it into a module.

i'd say we could try to combine them, but `gh-release` differs from `publish-release` a bit, especially with the strong defaults on `gh-release`. however, i'm totally open to PRing the asset uploading from `publish-release`, so at least both modules have the functionality :smile:

**Comment by maxogden** [comment]
"you can't share opinions, but you can share submodules" - me, just now

**Comment by ngoldman** [comment]
@remixz++ @maxogden++ agreed!

**Comment by ngoldman** [comment]
We've got support for asset uploads is `2.0.0`:

https://github.com/ngoldman/gh-release/releases/tag/v2.0.0

Thanks to @paulcpederson :+1: 

submodule: https://github.com/paulcpederson/gh-release-assets

should be usable by https://github.com/remixz/publish-release
