### ISSUE TITLE
Add workpath option to specify working directory

### ISSUE THREAD

**Issue by bcomnes** [ngoldman/gh-release#14]
Its unclear where getTargetCommitish (and other functions that use shell execution) are running.  We need a single path variable to run everything against.

**Comment by bcomnes** [comment]
I think adding a work path option will force a solution to this issue.  We'll have to write so that no particular path is assumed, allowing for better testing and programatic use, and it will also allow for a work path to be specified with the cli tool (not as useful in most situations).

**Comment by bcomnes** [comment]
I started a branch in https://github.com/bcomnes/gh-release/tree/workpath but it doesn't do anything yet.

**Comment by ngoldman** [comment]
:+1:

**Comment by ngoldman** [comment]
This makes sense to me as long as the current working directory is the default and `workpath` isn't required, and it looks like that's what you're thinking here: https://github.com/bcomnes/gh-release/commit/9c3177fa193f82e24cd5d307009142d85aa59311. We'll need to be careful as to how this is managed in the programmatic use case. Does this change mean we're adding another parameter to the function, or switching to an options object? If so this'll be a breaking change (which is fine).
