### ISSUE TITLE
git url in `repository.url` causes error

### ISSUE THREAD

**Issue by ngoldman** [ngoldman/gh-release#16]
We should support git urls (e.g. `git@github.com:Esri/esri-leaflet-renderers.git`), but we don't! Found this while watching @kneemer try to use the `gh-release` cli to release a new version of https://github.com/Esri/esri-leaflet-renderers.

Here's the line to refactor: https://github.com/ngoldman/gh-release/blob/master/lib/get-defaults.js#L8

**Comment by ngoldman** [comment]
@paulcpederson protip: if the commit says "fixes #16" (or [a bunch of other magic words](https://help.github.com/articles/closing-issues-via-commit-messages/)) and is merged it automatically closes the issue (I think it doesn't get caught if you add "issue" in there)

Thanks for the fix!

**Comment by paulcpederson** [comment]
@ngoldman yeah, knew about the automatic closing, wondered why that didn't work. Thanks for the info!

![](https://img.pandawhale.com/post-58933-karate-kid-youre-the-best-arou-afSz.gif)
