### ISSUE TITLE
Test for an updated changelog

### ISSUE THREAD

**Issue by bcomnes** [ngoldman/gh-release#21]
This way we won't merge till its noted in the changelog?  Just an idea.

**Comment by paulcpederson** [comment]
would probably be pretty straightforward to do that now that gh-release uses [changlog-parser](https://github.com/ngoldman/changelog-parser)

**Comment by ngoldman** [comment]
This seems like overkill to me -- there are definitely times when a PR is just for a typo or other minor things that don't deserve an update to the change log. I think tests should focus on ensuring functionality. `standard` is an exception but it does open up a can of worms about what tests should enforce.

**Comment by bcomnes** [comment]
K, sounds reasonable.
