### ISSUE TITLE
gh-release init

### ISSUE THREAD

**Issue by bcomnes** [ngoldman/gh-release#22]
Just about to use `gh-release` for the first time on a new package.  I'm realizing setting up a change log is tedious and it would be great if we had a tool that ran `npm init` and then `changelog init` or something like it to create a base changelog.  This is probably territory for a new module, but running `gh-release init` could trigger both or something along those lines.

Thoughts?  Ideas?  Does this already exist?  I have not googled yet.

**Comment by ngoldman** [comment]
I've thought about automating that. https://github.com/finnp/create-module is approaching something like that but doesn't work with changelogs and has some weird conventions like lowercasing README and things like that. I think it belongs in another module but I like the idea.

**Comment by bcomnes** [comment]
Made https://github.com/bcomnes/changelog-init.  We discussed how these fit together and this is out of bounds for `gh-release`.  Maybe for versioneer
