### ISSUE TITLE
gh-release without package.json?

### ISSUE THREAD

**Issue by bcomnes** [ngoldman/gh-release#26]
I was going to release something on github the other day, and realized that I was working inside of a something without a `package.json` and it wasn't javascript.  I did have a `CHANGELOG.md` and a git tag though.  How should we handle non-commonjs projects?

**Comment by ngoldman** [comment]
@bcomnes the description for the project is `Create a release for a node package on github.` and it relies pretty heavily on having a `package.json` present. We could loosen the defaults and expectations but supporting things outside of node might be out of scope for now... unless you have some good ideas for doing so while keeping it clean and focused.

**Comment by bcomnes** [comment]
I'm not really sure right now. I'll reopen if I have more of a clear idea.
