### ISSUE TITLE
v2 roadmap

### ISSUE THREAD

**Issue by ngoldman** [ngoldman/gh-release#27]
v1 is in decent working shape but I think this project needs to take some lessons from @remixz's https://github.com/remixz/publish-release.

### decoupling

I think we should restrict getting defaults from `package.json` and `CHANGELOG.md` to just the CLI, and pare down the Node API to requiring you to pass all relevant options yourself, as in https://github.com/remixz/publish-release#api-usage.

We need to move the authentication prompt, release preview, and confirmation steps out of the Node API -- they shouldn't be in there at all (my fault).

### tests

We need more test coverage! lol :sob:

Focusing on a pared-down node API will make covering that a lot easier, then we can cover the weirder stuff we're doing for the CLI use case.

### future features

* asset uploads
* emit events

Once that's complete it will be a lot easier to add asset uploads, emit events, and wrap this into the larger front-end release workflow we've been talking about with @paulcpederson.

---

Once the above is done I feel like this project is pretty much feature-complete unless I'm forgetting something.

Contributor-friends @bcomnes @paulcpederson let me know what you think.

**Comment by ngoldman** [comment]
Thinking about it we could just wrap `publish-release` and focus on the CLI since https://github.com/remixz/publish-release has the Node API portion pretty well covered.

**Comment by paulcpederson** [comment]
@ngoldman are you soliciting help on the above? decoupling/tests?

**Comment by ngoldman** [comment]
@paulcpederson yeah, but mostly feedback right now, i.e. does all that make sense

**Comment by paulcpederson** [comment]
I concur.

![](http://25.media.tumblr.com/bfa4dd35efa55b97701317d4117b45af/tumblr_mfnjb68lip1s14h9co1_400.gif)

**Comment by ngoldman** [comment]
![](http://img.pandawhale.com/post-5348-Star-Trek-deciding-gif-kEQX.gif)

**Comment by bcomnes** [comment]
Ya sounds good.  Kinda want to get the npm side working too

**Comment by ngoldman** [comment]
todos

- [x] decoupling refactor
- [ ] improved test coverage
- [ ] event emitter pattern for API
- [ ] asset uploads

**Comment by ngoldman** [comment]
I'm going to call this good enough for v2. Better to get asset upload officially released for now.

**Comment by bcomnes** [comment]
Very cool!  Nice work everyone

**Comment by paulcpederson** [comment]
:clap:
