### ISSUE TITLE
exit CLI process with 1 if release cancelled

### ISSUE THREAD

**Issue by ngoldman** [ngoldman/gh-release#31]
This enables the following workflow:

```
scripts: { release: "gh-release && npm publish" }
```

meaning w/ `npm run release`, `npm publish` would only run if `gh-release` exited successfully. if answering no to final confirmation prompt, should exit with `1` to fail and end rather than going on with publish step.

make sense @paulcpederson @bcomnes?

**Comment by ngoldman** [comment]
sorry @flet confusing this project temporarily with module-init which you contributed to

**Comment by paulcpederson** [comment]
Yes. :+1:  

I assumed it already worked that way, so I definitely am into it.

**Comment by ngoldman** [comment]
@paulcpederson nope https://github.com/ngoldman/gh-release/blob/master/index.js#L62 :(

this is also a project I did before I understood properly decoupling CLI from node API, been planning a refactor to use event emitter pattern internally and move the whole inquirer part to bin/cli

**Comment by paulcpederson** [comment]
https://github.com/ngoldman/gh-release/blob/master/bin/cli.js#L84

this should be `1` as well

**Comment by ngoldman** [comment]
@paulcpederson yep thanks good catch

**Comment by Flet** [comment]
@ngoldman No worries I'm having a great time reading this stuff :)

This is all accurate so far! :+1: 

Another little trick is using `||` to execute some other command if something exits non-zero
`gh-release && npm publish || echo Something went terribly wrong`

**Comment by Flet** [comment]
Neat module btw! I like the idea of putting changelog info in the release. Its a lot richer than just using `npm version` generated tags. Will try it out for sure.

**Comment by Flet** [comment]
it meshes with a little idea I had the other day... 
`lazy-changelog` which would push commit messages since the last tag into CHANGELOG.md...
Sometimes raw commit messages are good enough for tiny modules. It could just be used as a seed before hand editing too.

But Imagine: `scripts: { release: "lazy-changelog && gh-release && npm publish" }`

**Comment by ngoldman** [comment]
@Flet sounds interesting! I've been thinking about having a major/minor/patch type of flag to bump version in `package.json` and change "Unreleased" to that version before the release happens. Something like your `lazy-changelog` idea would work well with that.

**Comment by ngoldman** [comment]
@paulcpederson one last question for this thread. What about dry runs?

Right now it exits with `0`: https://github.com/ngoldman/gh-release/blob/v1.1.7/index.js#L59
