### ISSUE TITLE
[github-auth] accept API token instead of user/pass

### ISSUE THREAD

**Issue by ngoldman** [ngoldman/gh-release#5]

**Comment by ngoldman** [comment]
@bcomnes do you think https://github.com/rvagg/ghauth will do the trick? might also mean gh-release wouldn't need to rely on the `github` package.

**Comment by bcomnes** [comment]
Uh oh, getting errors on the head of auth now (https://github.com/ngoldman/gh-release/commit/cf511edd4379fc00b642dae654227caadc23462c):

```sh
Bret-MBR:gh-release-test bret$ gh-release 
{ tag_name: 'v1.0.1',
  target_commitish: '40c8e8708a315a00b7673eabbc27a83438305c10',
  name: 'v1.0.1',
  body: '* Made another release\n\n',
  owner: 'bcomnes',
  repo: 'gh-release-test',
  draft: false,
  prerelease: false }
? does this look right? Yes
{ [Error: {"message":"Server Error","documentation_url":"https://developer.github.com/v3"}]
  message: '{"message":"Server Error","documentation_url":"https://developer.github.com/v3"}',
  code: 500 }
```

**Comment by bcomnes** [comment]
Looks ready to merge to master to me if your cool with that.

**Comment by ngoldman** [comment]
@bcomnes I'm still doing a little work on `auth` -- I'll open a PR in a little bit.

**Comment by ngoldman** [comment]
@bcomnes I ran into the 500 error from github too when forgetting to push for https://github.com/bcomnes/gh-release-test -- note to self to check if the commit being released is on github first then display a better error message.
